version: "3"

services:
  # database
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 9EY449gpWPR7aGc7
    ports:
      - '33306:3306'
    volumes:
      - ./mysql:/etc/mysql/mysql.conf.d
      - ./sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 9EY449gpWPR7aGc7
    links:
      - mysql:mysql
    ports:
      - 38000:80

  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass ptcnptcn
    ports:
      - '36379:6379'
    volumes:
      - ./data/redis:/data

  # etcd
  # etcd:
  #   image: quay.io/coreos/etcd:v3.3.18
  #   container_name: etcd
  #   command: /usr/local/bin/etcd --name s1 --data-dir /etcd-data --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379 --listen-peer-urls http://0.0.0.0:2380 --initial-advertise-peer-urls http://0.0.0.0:2380 --initial-cluster s1=http://0.0.0.0:2380
  #   volumes:
  #     - ./data/etcd:/etcd-data
  #   ports:
  #     - "32379:2379"
  #     - "32380:2380"

  # consul
  consul:
    image: consul:latest
    container_name: consul
    environment: 
      CONSUL_HTTP_ADDR: 127.0.0.1:8500
    command: consul agent -config-file=/consul/config
    ports:
      - '38500:8500'
    volumes:
      - ./consul:/consul/config
      - ./data/consul:/consul/data

  # vault
  vault:
    image: vault:latest
    container_name: vault
    environment: 
      VAULT_ADDR: http://127.0.0.1:8200
    command: vault server -config=/vault/config/config.hcl
    cap_add: 
      - IPC_LOCK 
    ports:
      - '38200:8200'
    volumes:
      - ./vault:/vault/config
      - ./data/vault/file:/vault/file
      - ./data/vault/logs:/vault/logs
  
  # loki
  loki:
    image: grafana/loki
    volumes:
      - ./log/grafana:/var/log
    ports:
      - "33100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  # prometheus
  prometheus:
    image: prom/prometheus
    volumes:
      - ./data/prometheus:/prometheus/data
      - ./log/prometheus:/var/log
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "39090:9090"

  # nodeexporter:
  #   image: prom/node-exporter
  #   volumes:
  #     - ./log/node-exporter:/var/log
  #   ports:
  #     - "39100:9100"

  # promtail
  promtail:
    image: grafana/promtail
    volumes:
      - /var/log:/var/log
      - ./log/promtail/tmp:/tmp
      - ./promtail/config:/etc/promtail
    command: -config.file=/etc/promtail/docker-config.yaml
    ports:
      - "39080:9080"
  
  # grafana
  grafana:
    image: grafana/grafana
    ports:
      - "33000:3000"

  # gateway
  gateway-api:
    build: ./go13
    container_name: gateway-api
    command: bash -c "syslogd && make build && make run-api"
    environment: 
      VAULT_TOKEN: ${VAULT_TOKEN}
    volumes:
      - ../gateway:/go/src/myapp
    ports:
      - "38080:8080"
  
  gateway-web:
    build: ./go13
    container_name: gateway-web
    command: bash -c "syslogd && make build && make run-web"
    environment: 
      VAULT_TOKEN: ${VAULT_TOKEN}
    volumes:
      - ../gateway:/go/src/myapp
    ports:
      - "38081:8080"

  # srv & api
  user-srv:
    build: ./go13
    container_name: user-srv
    command: bash -c "syslogd && make build && make run"
    environment: 
      VAULT_TOKEN: ${VAULT_TOKEN}
    volumes:
      - ../user-srv:/go/src/myapp
      - /var/log:/var/log

  user-api:
    container_name: user-api
    build: ./go13
    command: bash -c "syslogd && make build && make run"
    environment: 
      VAULT_TOKEN: ${VAULT_TOKEN}
    volumes:
      - ../user-api:/go/src/myapp
      - /var/log:/var/log